version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: inventory_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - inventory_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: inventory_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/inventory?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - inventory_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: inventory_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - inventory_network

volumes:
  mongodb_data:

networks:
  inventory_network:
    driver: bridge
